### PR TITLE
URL fix to display result

### PR DESCRIPTION
**Pull request by scorpionhiccup**
The URL reverse was initially going to was not working correctly so I have changed the namespace to report(of interface). Also the result page was giving error as task.object_id was not getting initialized. Also all the reports are getting queued.

### CODE REVIEW

**Comment by scorpionhiccup** [comment]
I don't understand why the object_id field in the Task model is not being initially to pass in the d3.json call in the result.html page..

**Comment by pdelsante** [comment]
Nice catch on the wrong URL name in the `HttpResponseRedirect`, I had renamed the view but I had forgotten that line!

However, I am not merging your request as-is, as there are some other points that are unclear to me. For example, you probably forgot a test line here:

```
--- a/interface/views.py
+++ b/interface/views.py
@@ -94,6 +94,7 @@ def reports(request, status='any', pagination_start=0, pagination_len=50):

 @login_required
 def report(request, task_id):
+    print task_id
     context = {
         'active_tab': 'reports',
         'task'      : get_object_or_404(Task, pk=task_id)
```

As for the object_id, it should only be there when a task is either finished or failed: this means that Thug has already finished running and has already returned the `ObjectId()` assigned to the corresponding entry in the `db.analyses` collection. I am not sure I get what you mean, but I will get a closer look at the code as soon as I can (probably tomorrow) and I'll let you know.

In the meanwhile, thanks for your time!

**Comment by pdelsante** [comment]
By the way, could you please make a separate pull request for the `HttpResponseRedirect` fix so that I can accept it straight away? I want to give you credits for that!

Thanks again,
Pietro

**Comment by scorpionhiccup** [comment]
Hey, yes I agree the object_id should get value when a task is either finished or failed but in my case the line d3.json sends a request  when the task was in queue. This was a small bug as the object_id being passed in the url line (315 of html file for report), was giving error that there was no arguement passed while calling json_tree method. So what should it do when the status is none of the above? Yes, I will make a seperate pull request for HttpResponseRedirect by today..
Thanking you for prompt reply

**Comment by scorpionhiccup** [comment]
Also should I make a seperate pull request or just remove the print  statement from this pull request?

**Comment by pdelsante** [comment]
I see no point in using a print statement in a Django view (I assume you used it as a temporary test), so you could just remove it.

**Comment by scorpionhiccup** [comment]
Yes, no problem. Done

**Comment by scorpionhiccup** [comment]
Regarding the Template change that I had initially made, should that be added or not? As the problem comes when the task.object_id is empty string(when task status is still in processing state) as is happening with me as of now. Further it can be a safe way to not cause unwanted ticket errors.

**Pull request merged**
